on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - id: deploy
        uses: google-github-actions/deploy-cloud-functions@main
        with:
          name: rainfall-data-2
          runtime: python38
          credentials: ${{ secrets.GCP_SA_KEY }}
          memory_mb: 128
          region: us-central1
          source_dir: /src/
